apiVersion: kustomize.config.k8s.io/v1beta1  
kind: Kustomization  

resources:  
- ../../../base/frontend

patches:  
- patch: |-  
    - op: replace  
      path: /spec/replicas  
      value: 3  
    - op: replace  
      path: /spec/template/spec/containers/0/resources/limits/cpu  
      value: 500m  
    - op: replace  
      path: /spec/template/spec/containers/0/resources/limits/memory  
      value: 512Mi  
- target:  
    kind: ConfigMap  
    name: frontend-config  
  patch: |-  
    - op: replace  
      path: /data/LOG_LEVEL  
      value: error
