apiVersion: kustomize.config.k8s.io/v1beta1  
kind: Kustomization  

resources:  
- ../../base/products  

patches:  
- patch: |-  
    - op: replace  
      path: /spec/replicas  
      value: 1  
    - op: replace  
      path: /spec/template/spec/containers/0/image  
      value: null32sys/products:dev  
- target:  
    kind: ConfigMap  
    name: products-config  
  patch: |-  
    - op: replace  
      path: /data/APP_ENV  
      value: staging  
    - op: replace  
      path: /data/LOG_LEVEL  
      value: debug
