apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend

#patchesStrategicMerge:
#  - deployment-patch.yaml  # Use strategic merge patch for deployment
#  - configmap-patch.yaml    # Use strategic merge patch for configmap

# If you want to use JSON patches, you can define them separately
patches:
  - target:
      kind: Deployment
      name: orders-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: null32sys/products:dev  # Ensure this is a valid image name
  - target:
      kind: ConfigMap
      name: products-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: development
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
