apiVersion: kustomize.config.k8s.io/v1beta1  
kind: Kustomization  

resources:  
- deployment.yaml  
- service.yaml  
- hpa.yaml  
- ingress.yaml  
- configmap.yaml  

images:  
- name: null32sys/orders
  newTag: 1.0.0  

commonLabels:  
  app: orders
  tier: orders
